global using Microsoft.AspNetCore.Http;
global using AutoMapper;
global using BLL.ModelVM.Order;
global using DAL.Enities;
global using System.Linq.Expressions;
global using BLL.Services.Abstract;
global using DAL.DataBase;
global using DAL.Repo.Abstract;
global using System.Collections.Generic;